#!/bin/bash
set -eufo pipefail

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

printf "%s\n" 'starting remote machines'
"$here/script/start-remotes" &
sleep 5
printf "%s\n" 'starting user machine'
exec "$here/script/start-user"
