#!/bin/bash
set -euo pipefail
shopt -s failglob

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
machines_dir="$(pwd)"
mkdir -p "$1"
cd "$1"
export wan_dir="$(pwd)"

for machine_dir in "$machines_dir"/*; do
  cd "$machine_dir" && "$here/machine-prepare"
done
cd "$machines_dir"
